"use client"

import { useState } from "react"
import Link from "next/link"
import { ArrowRight, BarChart3, Building2, CheckCircle2, CircleHelp, CreditCard, MapPin, Network, ShieldCheck, Users, WalletCards } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Logo, SectionTitle, StatusBadge } from "@/components/stillacon-shell"
import { createClient } from "@/lib/supabase/client"

const cards = [{ icon: Users, title: "Customers", copy: "Know who is using your service." }, { icon: CreditCard, title: "Payments", copy: "Track transactions automatically." }, { icon: WalletCards, title: "Earnings", copy: "See your share clearly." }, { icon: Network, title: "Connectivity", copy: "Monitor your location." }, { icon: BarChart3, title: "Automation", copy: "Let StillaCon handle repetitive operations." }]
const demoCustomers = [{ name: "Customer 001", plan: "1 Week", status: "ACTIVE", expiry: "24 Sep 2026" }, { name: "Customer 002", plan: "24 Hours", status: "ACTIVE", expiry: "18 Sep 2026" }, { name: "Customer 003", plan: "1 Month", status: "EXPIRING", expiry: "30 Sep 2026" }]
const demoTransactions = [{ date: "18 Sep 2026", time: "10:42", plan: "1 Week", amount: "GHS 25", merchant: "GHS 12.50", status: "SUCCESS" }, { date: "18 Sep 2026", time: "09:18", plan: "24 Hours", amount: "GHS 15", merchant: "GHS 7.50", status: "SUCCESS" }, { date: "17 Sep 2026", time: "18:03", plan: "1 Month", amount: "GHS 75", merchant: "GHS 37.50", status: "SUCCESS" }]

export function MerchantHeader() { return <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Logo /><nav className="hidden items-center gap-6 text-sm text-muted-foreground md:flex"><Link href="/merchant" className="hover:text-foreground">Merchant</Link><Link href="/about" className="hover:text-foreground">About</Link><Link href="/support" className="hover:text-foreground">Support</Link></nav><div className="flex items-center gap-2"><Link href="/login" className="hidden px-3 py-2 text-sm text-muted-foreground hover:text-foreground sm:block">Merchant login</Link><Link href="/merchant/apply" className="inline-flex h-9 items-center gap-2 rounded-lg bg-primary px-3 text-sm font-medium text-primary-foreground">Apply now <ArrowRight data-icon="inline-end" /></Link></div></header> }
export function MerchantLanding() { return <main className="min-h-screen overflow-hidden"><MerchantHeader /><section className="mx-auto max-w-7xl px-5 pb-20 pt-20 lg:px-8 lg:pb-28 lg:pt-28"><div className="max-w-3xl"><p className="mb-5 text-[10px] font-bold tracking-[.24em] text-primary">STILLACON MERCHANT</p><h1 className="text-5xl font-semibold leading-[1.02] tracking-[-.05em] text-balance md:text-7xl">Turn connectivity into a <span className="text-primary">business.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">Operate an approved StillaCon connectivity location with customer management, payments, access management, reporting and revenue tracking in one platform.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/merchant/apply" className="inline-flex h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground">Apply to become a merchant <ArrowRight data-icon="inline-end" /></Link><Link href="/login" className="inline-flex h-11 items-center rounded-xl border border-border bg-secondary px-4 text-sm font-semibold">Merchant login</Link></div><p className="mt-7 flex max-w-xl items-start gap-2 text-xs leading-5 text-muted-foreground"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-primary" />Merchant participation is subject to Stilla Systems approval and an eligible, authorized connectivity arrangement.</p></div></section><section className="border-y border-border/70 bg-card/30"><div className="mx-auto grid max-w-7xl gap-4 px-5 py-16 sm:grid-cols-2 lg:grid-cols-5 lg:px-8">{cards.map(({ icon: Icon, title, copy }) => <div key={title} className="rounded-2xl border border-border/70 bg-card/60 p-5"><Icon className="size-5 text-primary" /><h2 className="mt-8 text-sm font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy}</p></div>)}</div></section></main> }

function MerchantNav() { return <aside className="hidden w-64 shrink-0 border-r border-border/70 bg-card/40 p-5 lg:block"><Logo /><p className="mb-3 mt-12 px-3 text-[10px] font-bold tracking-[.2em] text-primary">MERCHANT CONSOLE</p><nav className="flex flex-col gap-1">{[["/merchant/dashboard","Overview"],["/merchant/customers","Customers"],["/merchant/transactions","Transactions"],["/merchant/earnings","Earnings"],["/merchant/locations","Locations"],["/support","Support"]].map(([href,label]) => <Link key={href} href={href} className="rounded-xl px-3 py-3 text-sm text-muted-foreground hover:bg-accent/60 hover:text-foreground">{label}</Link>)}</nav><div className="mt-10 rounded-2xl border border-primary/15 bg-primary/5 p-4"><p className="text-xs font-semibold">Approved location</p><p className="mt-1 text-[11px] leading-5 text-muted-foreground">Merchant workspace · DEMO</p></div></aside> }
export function MerchantShell({ children }: { children: React.ReactNode }) { return <div className="flex min-h-screen"><MerchantNav /><div className="min-w-0 flex-1"><header className="flex h-20 items-center justify-between border-b border-border/70 px-5 lg:px-8"><div><p className="text-[10px] font-bold tracking-[.2em] text-primary">STILLACON / MERCHANT</p><h1 className="mt-1 text-lg font-semibold">Merchant workspace</h1></div><div className="flex items-center gap-3"><span className="hidden text-xs text-muted-foreground sm:block">Demo workspace</span><div className="grid size-9 place-items-center rounded-full bg-primary text-xs font-bold text-primary-foreground">SM</div></div></header><main className="mx-auto max-w-[1400px] p-5 lg:p-8">{children}</main></div></div> }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-2xl border border-border/70 bg-card/70 p-5"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-3 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-2 text-xs text-primary">{detail}</p></div> }
export function MerchantDashboard() { return <MerchantShell><SectionTitle eyebrow="OVERVIEW · DEMO DATA" title="Good morning, merchant" description="A simple operating view for your approved StillaCon location." action={<StatusBadge status="ONLINE" />} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Live customers" value="24" detail="Current location · DEMO" /><Metric label="Today's sales" value="GHS 300" detail="12 transactions · DEMO" /><Metric label="Your earnings" value="GHS 150" detail="Pending allocation · DEMO" /><Metric label="Location" value="Online" detail="StillaCon — Merchant Location" /></div><div className="mt-8 grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><section className="rounded-2xl border border-border/70 bg-card/60 p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold tracking-[.18em] text-primary">ACTIVE PLAN SALES</p><h2 className="mt-2 text-lg font-semibold">This month</h2></div><BarChart3 className="size-5 text-muted-foreground" /></div><div className="mt-7 flex flex-col gap-5">{[["24 Hours","8","40%"],["1 Week","10","62%"],["1 Month","6","38%"]].map(([name,count,width]) => <div key={name}><div className="flex justify-between text-sm"><span>{name}</span><span className="text-muted-foreground">{count} sales</span></div><div className="mt-2 h-2 rounded-full bg-secondary"><div className="h-2 rounded-full bg-primary" style={{ width }} /></div></div>)}</div></section><section className="rounded-2xl border border-border/70 bg-card/60 p-6"><p className="text-xs font-bold tracking-[.18em] text-primary">QUICK ACTIONS</p><div className="mt-5 flex flex-col gap-2">{[["/merchant/customers","Customers",Users],["/merchant/transactions","Transactions",CreditCard],["/merchant/earnings","Earnings",WalletCards],["/merchant/locations","Locations",MapPin]].map(([href,label,Icon]) => <Link key={label as string} href={href as string} className="flex items-center justify-between rounded-xl border border-border/70 px-4 py-3 text-sm hover:bg-accent/50"><span className="flex items-center gap-3">{Icon && <Icon className="size-4 text-primary" />}{label as string}</span><ArrowRight className="size-4 text-muted-foreground" /></Link>)}</div></section></div></MerchantShell> }
function DataTable({ children }: { children: React.ReactNode }) { return <div className="overflow-x-auto rounded-2xl border border-border/70 bg-card/60"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-border/70 text-xs text-muted-foreground">{children}</thead></table></div> }
export function MerchantCustomers() { return <MerchantShell><SectionTitle eyebrow="CUSTOMERS" title="Customers" description="Only customers associated with your approved locations are shown." /><DataTable><tr><th className="p-4 font-medium">Customer</th><th className="p-4 font-medium">Plan</th><th className="p-4 font-medium">Status</th><th className="p-4 font-medium">Expiry</th></tr><tbody>{demoCustomers.map(row => <tr key={row.name} className="border-b border-border/50 last:border-0"><td className="p-4">{row.name}</td><td className="p-4 text-muted-foreground">{row.plan}</td><td className="p-4"><StatusBadge status={row.status} /></td><td className="p-4 text-muted-foreground">{row.expiry}</td></tr>)}</tbody></DataTable></MerchantShell> }
export function MerchantTransactions() { return <MerchantShell><SectionTitle eyebrow="TRANSACTIONS · DEMO DATA" title="Transactions" description="Payment records are read-only. Revenue shares are ledger values, not withdrawable balances." /><DataTable><tr><th className="p-4 font-medium">Date / time</th><th className="p-4 font-medium">Plan</th><th className="p-4 font-medium">Amount</th><th className="p-4 font-medium">Merchant share</th><th className="p-4 font-medium">Status</th></tr><tbody>{demoTransactions.map(row => <tr key={row.date + row.time} className="border-b border-border/50 last:border-0"><td className="p-4">{row.date}<span className="ml-2 text-muted-foreground">{row.time}</span></td><td className="p-4 text-muted-foreground">{row.plan}</td><td className="p-4">{row.amount}</td><td className="p-4">{row.merchant}</td><td className="p-4"><StatusBadge status={row.status} /></td></tr>)}</tbody></DataTable></MerchantShell> }
export function MerchantEarnings() { return <MerchantShell><SectionTitle eyebrow="EARNINGS · DEMO DATA" title="Earnings" description="Ledger foundations are in place. Automated payouts are not enabled." /><div className="grid gap-4 sm:grid-cols-3"><Metric label="Total revenue" value="GHS 300" detail="Gross · DEMO" /><Metric label="Merchant earnings" value="GHS 150" detail="Pending availability · DEMO" /><Metric label="Paid out" value="GHS 0" detail="No payouts enabled" /></div><div className="mt-8 rounded-2xl border border-border/70 bg-card/60 p-6"><h2 className="text-lg font-semibold">Ledger status</h2><div className="mt-5 grid gap-3 sm:grid-cols-4">{[["PENDING","GHS 150"],["PROCESSING","GHS 0"],["PAID","GHS 0"],["VOIDED","GHS 0"]].map(([status,amount]) => <div key={status} className="rounded-xl bg-secondary/60 p-4"><p className="text-[10px] font-bold tracking-[.15em] text-muted-foreground">{status}</p><p className="mt-3 text-xl font-semibold">{amount}</p></div>)}</div></div></MerchantShell> }
export function MerchantLocations() { return <MerchantShell><SectionTitle eyebrow="LOCATIONS" title="Locations" description="Location activation remains controlled by Stilla Systems. You cannot activate your own location." /><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-border/70 bg-card/60 p-6"><div className="flex items-start justify-between"><div><MapPin className="size-5 text-primary" /><h2 className="mt-5 text-lg font-semibold">StillaCon — Merchant Location</h2><p className="mt-2 text-sm text-muted-foreground">Accra · Greater Accra</p></div><StatusBadge status="ACTIVE" /></div><div className="mt-7 grid grid-cols-2 gap-4 text-sm"><div><p className="text-muted-foreground">Connectivity</p><p className="mt-1 font-medium text-primary">ONLINE</p></div><div><p className="text-muted-foreground">Connected users</p><p className="mt-1 font-medium">24 · DEMO</p></div></div></div></div></MerchantShell> }
function StaticApplyForm() { return <main className="min-h-screen"><MerchantHeader /><section className="mx-auto max-w-3xl px-5 pb-20 pt-14 lg:px-8"><p className="text-[10px] font-bold tracking-[.24em] text-primary">MERCHANT APPLICATION</p><h1 className="mt-4 text-4xl font-semibold tracking-tight md:text-6xl">Apply to become a merchant.</h1><p className="mt-5 max-w-2xl leading-7 text-muted-foreground">Tell us about your business and eligible connectivity setup. Every application is reviewed by Stilla Systems; submission does not guarantee approval.</p><form className="mt-10 grid gap-5 rounded-3xl border border-border/70 bg-card/60 p-6 md:grid-cols-2 md:p-8">{[["Full name","full-name"],["Business name","business-name"],["Phone","phone"],["Email","email"],["Business / location address","address"],["City","city"],["Region","region"],["Connectivity provider","provider"],["Connectivity plan","plan"],["Equipment / setup information","equipment"],["Intended service area","service-area"],["Additional verification information","verification"]].map(([label,id]) => <label key={id} className={id === "address" || id === "equipment" || id === "service-area" || id === "verification" ? "md:col-span-2" : ""}><span className="mb-2 block text-xs font-medium">{label}</span>{["address","equipment","service-area","verification"].includes(id) ? <textarea id={id} name={id} required className="min-h-24 w-full rounded-xl border border-input bg-background/50 px-3 py-3 text-sm outline-none focus:ring-2 focus:ring-ring" /> : <input id={id} name={id} type={id === "email" ? "email" : "text"} required className="h-11 w-full rounded-xl border border-input bg-background/50 px-3 text-sm outline-none focus:ring-2 focus:ring-ring" />}</label>)}<div className="md:col-span-2"><Button type="submit" className="h-11 w-full">Submit application <ArrowRight data-icon="inline-end" /></Button><p className="mt-3 text-center text-xs text-muted-foreground">Your information will be reviewed securely by Stilla Systems.</p></div></form></section></main> }
export function ApplyForm() {
  const [pending, setPending] = useState(false)
  const [message, setMessage] = useState<string | null>(null)
  const [submitted, setSubmitted] = useState(false)

  async function submitApplication(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setPending(true)
    setMessage(null)
    const form = new FormData(event.currentTarget)
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) {
      setMessage("Please sign in before submitting a merchant application.")
      setPending(false)
      return
    }
    const applicationNumber = `APP-${Date.now()}`
    const { error } = await supabase.from("merchant_applications").insert({
      application_number: applicationNumber,
      applicant_user_id: user.id,
      full_name: form.get("full-name"),
      business_name: form.get("business-name"),
      phone: form.get("phone"),
      email: form.get("email"),
      business_address: form.get("address"),
      city: form.get("city"),
      region: form.get("region"),
      connectivity_provider: form.get("provider"),
      connectivity_plan: form.get("plan"),
      equipment_description: form.get("equipment"),
      intended_service_area: form.get("service-area"),
      verification_information: { details: form.get("verification") },
    })
    if (error) setMessage("We could not submit your application. Please review the form and try again.")
    else setSubmitted(true)
    setPending(false)
  }

  if (submitted) return <ApplicationReceived />
  return <main className="min-h-screen"><MerchantHeader /><section className="mx-auto max-w-3xl px-5 pb-20 pt-14 lg:px-8"><p className="text-[10px] font-bold tracking-[.24em] text-primary">MERCHANT APPLICATION</p><h1 className="mt-4 text-4xl font-semibold tracking-tight md:text-6xl">Apply to become a merchant.</h1><p className="mt-5 max-w-2xl leading-7 text-muted-foreground">Tell us about your business and eligible connectivity setup. Every application is reviewed by Stilla Systems.</p><form onSubmit={submitApplication} className="mt-10 grid gap-5 rounded-3xl border border-border/70 bg-card/60 p-6 md:grid-cols-2 md:p-8">{[["Full name","full-name"],["Business name","business-name"],["Phone","phone"],["Email","email"],["Business / location address","address"],["City","city"],["Region","region"],["Connectivity provider","provider"],["Connectivity plan","plan"],["Equipment / setup information","equipment"],["Intended service area","service-area"],["Additional verification information","verification"]].map(([label,id]) => <label key={id} className={["address","equipment","service-area","verification"].includes(id) ? "md:col-span-2" : ""}><span className="mb-2 block text-xs font-medium">{label}</span>{["address","equipment","service-area","verification"].includes(id) ? <textarea id={id} name={id} required className="min-h-24 w-full rounded-xl border border-input bg-background/50 px-3 py-3 text-sm outline-none focus:ring-2 focus:ring-ring" /> : <input id={id} name={id} type={id === "email" ? "email" : "text"} required className="h-11 w-full rounded-xl border border-input bg-background/50 px-3 text-sm outline-none focus:ring-2 focus:ring-ring" />}</label>)}<div className="md:col-span-2"><Button type="submit" disabled={pending} className="h-11 w-full">{pending ? "Submitting…" : "Submit application"} <ArrowRight data-icon="inline-end" /></Button>{message && <p role="alert" className="mt-3 text-center text-xs text-destructive">{message}</p>}<p className="mt-3 text-center text-xs text-muted-foreground">Your information will be reviewed securely by Stilla Systems.</p></div></form></section></main>
}

export function AdminMerchants() { return <div className="min-h-screen"><header className="border-b border-border/70 px-5 py-5 lg:px-8"><Logo /></header><main className="mx-auto max-w-7xl px-5 py-12 lg:px-8"><SectionTitle eyebrow="OPERATIONS / MERCHANTS" title="Merchant management" description="Review applications and control merchant lifecycle transitions." /><div className="grid gap-4 sm:grid-cols-3"><Metric label="Pending applications" value="3" detail="Needs review" /><Metric label="Approved" value="8" detail="Controlled access" /><Metric label="Active locations" value="5" detail="Verified sources" /></div><div className="mt-8 rounded-2xl border border-border/70 bg-card/60 p-6"><div className="flex items-center gap-3"><CircleHelp className="size-5 text-primary" /><p className="text-sm">Administrative actions should be implemented through authorized server-side operations and recorded in audit logs.</p></div></div></main></div> }
export function ApplicationReceived() { return <main className="min-h-screen"><MerchantHeader /><section className="mx-auto max-w-xl px-5 py-24 text-center"><div className="mx-auto grid size-16 place-items-center rounded-full bg-primary/10 text-primary"><CheckCircle2 /></div><h1 className="mt-7 text-4xl font-semibold tracking-tight">Application received.</h1><p className="mt-4 leading-7 text-muted-foreground">Your StillaCon Merchant application has been submitted and will be reviewed by Stilla Systems.</p><Link href="/merchant" className="mt-8 inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground">Back to merchant</Link></section></main> }
