import Image from "next/image"
import Link from "next/link"
import { Activity, ArrowUpRight, Bell, ChevronRight, CircleHelp, CreditCard, LayoutDashboard, Menu, Network, Settings, Smartphone, Users, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { adminNav, navItems, statusTone } from "@/lib/stillacon-data"
import { SignOutButton } from "@/components/auth-forms"
import { AnimatedWifi } from "@/components/animated-wifi"

export function Logo({ compact = false }: { compact?: boolean }) { return <Link href="/" className="flex items-center gap-3"><Image src="/stilla-logo-new.jpg" alt="Stilla Systems" width={compact ? 36 : 42} height={compact ? 36 : 42} className="rounded-xl object-cover shadow-[0_0_24px_rgba(39,182,246,.3)]" priority />{!compact && <span><span className="block text-sm font-bold tracking-[.22em]">STILLA</span><span className="block text-[10px] tracking-[.28em] text-primary">CONNECT</span></span>}</Link> }
export function StatusBadge({ status }: { status: string }) { const tone = statusTone(status); return <span className={`status-${tone} inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-bold tracking-[.16em]`}><span className="size-1.5 rounded-full bg-current" />{status}</span> }
export function PublicHeader() { return <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Logo /><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><Link href="/plans" className="hover:text-foreground">Plans</Link><Link href="/about" className="hover:text-foreground">About</Link><Link href="/support" className="hover:text-foreground">Support</Link></nav><div className="flex items-center gap-2"><Link href="/login" className="hidden px-3 py-2 text-sm text-muted-foreground hover:text-foreground sm:block">Sign in</Link><Link href="/connect" className="inline-flex h-7 items-center gap-1 rounded-lg bg-primary px-2.5 text-[0.8rem] font-medium text-primary-foreground hover:bg-primary/80">Get connected <ArrowUpRight data-icon="inline-end" /></Link></div></header> }
function SideNav({ admin = false }: { admin?: boolean }) { const items = admin ? adminNav : navItems; return <aside className="hidden w-64 shrink-0 border-r border-border/70 bg-[#071522]/80 p-5 lg:block"><Logo /><div className="mt-12 mb-3 px-3 text-[10px] font-bold tracking-[.2em] text-muted-foreground">{admin ? "OPERATIONS" : "MY CONNECTION"}</div><nav className="flex flex-col gap-1">{items.map(item => <Link key={item.href} href={item.href} className="flex items-center justify-between rounded-xl px-3 py-3 text-sm text-muted-foreground hover:bg-accent/60 hover:text-foreground"><span className="flex items-center gap-3"><LayoutDashboard className="size-4" />{item.label}</span>{item.label === "Overview" && <span className="size-1.5 rounded-full bg-primary" />}</Link>)}</nav><div className="mt-10 rounded-2xl border border-primary/15 bg-primary/5 p-4"><AnimatedWifi size={28} /><p className="mt-4 text-xs font-semibold">Connected to StillaCon</p><p className="mt-1 text-[11px] leading-5 text-muted-foreground">Your connection is secure and active.</p></div><SignOutButton /></aside> }
export function AppHeader({ admin = false }: { admin?: boolean }) { return <header className="flex h-20 items-center justify-between border-b border-border/70 px-5 lg:px-8"><div><p className="text-[10px] font-bold tracking-[.2em] text-primary">{admin ? "STILLACON / OPERATIONS" : "STILLACON / CUSTOMER"}</p><h1 className="mt-1 text-lg font-semibold">{admin ? "Network overview" : "Good morning, Kwame"}</h1></div><div className="flex items-center gap-2"><Button variant="ghost" size="icon" aria-label="Notifications"><Bell /></Button><div className="ml-2 grid size-9 place-items-center rounded-full bg-gradient-to-br from-cyan-300 to-blue-700 text-xs font-bold text-slate-950">KM</div></div></header> }
export function AppShell({ children, admin = false }: { children: React.ReactNode; admin?: boolean }) { return <div className="flex min-h-screen"><SideNav admin={admin} /><div className="min-w-0 flex-1"><AppHeader admin={admin} /><main className="mx-auto max-w-[1400px] p-5 lg:p-8">{children}</main></div></div> }
export function SectionTitle({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div>{eyebrow && <p className="mb-2 text-[10px] font-bold tracking-[.22em] text-primary">{eyebrow}</p>}<h2 className="text-2xl font-semibold tracking-tight lg:text-3xl">{title}</h2>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p>}</div>{action}</div> }
export const icons = { users: Users, activity: Activity, wallet: CreditCard, chart: ArrowUpRight, phone: Smartphone, settings: Settings, help: CircleHelp, menu: Menu, close: X, chevron: ChevronRight }
