export type Status = "ACTIVE" | "EXPIRED" | "SUSPENDED" | "PENDING" | "SUCCESS" | "FAILED" | "AUTHORIZED" | "BLOCKED" | "ONLINE" | "DEGRADED" | "OFFLINE"

export const customer = { name: "Kwame Mensah", id: "STC-000127", phone: "+233 24 555 0184", email: "kwame.mensah@example.com" }
export const plan = { name: "Monthly", price: "GHS 149", speed: "25 Mbps", duration: "30 days", description: "Reliable community Internet for everyday work, learning and entertainment." }
export const subscription = { status: "ACTIVE" as const, expiry: "30 September 2026", daysRemaining: 14 }
export const devices = [{ name: "Kwame’s iPhone", type: "iPhone 15 Pro", status: "AUTHORIZED" as const, lastSeen: "Just now", usage: "2.4 GB" }, { name: "MacBook Air", type: "Laptop", status: "PENDING" as const, lastSeen: "Yesterday", usage: "8.1 GB" }]
export const payments = [{ ref: "STC-8F42A1", date: "01 Sep 2026", plan: "Monthly", amount: "GHS 149", status: "SUCCESS" as const }, { ref: "STC-7C19D0", date: "01 Aug 2026", plan: "Monthly", amount: "GHS 149", status: "SUCCESS" as const }, { ref: "STC-62A8EE", date: "01 Jul 2026", plan: "Monthly", amount: "GHS 149", status: "SUCCESS" as const }]
export const plans = [{ name: "Daily", price: "GHS 12", speed: "10 Mbps", duration: "24 hours", label: "For quick access" }, { name: "Weekly", price: "GHS 49", speed: "20 Mbps", duration: "7 days", label: "For flexible routines" }, { name: "Monthly", price: "GHS 149", speed: "25 Mbps", duration: "30 days", label: "Best value" }]
export const adminStats = [{ label: "Total customers", value: "2,847", delta: "+12.4%", icon: "users" }, { label: "Active subscriptions", value: "1,984", delta: "+8.2%", icon: "activity" }, { label: "Pending payments", value: "36", delta: "Needs review", icon: "wallet" }, { label: "Monthly revenue", value: "GHS 284k", delta: "+18.7%", icon: "chart" }]
export const recentCustomers = [{ name: "Ama Boateng", id: "STC-000128", plan: "Weekly", status: "ACTIVE" }, { name: "Daniel Owusu", id: "STC-000129", plan: "Monthly", status: "ACTIVE" }, { name: "Nana Yaa", id: "STC-000130", plan: "Daily", status: "PENDING" }, { name: "Kojo Asante", id: "STC-000131", plan: "Monthly", status: "EXPIRED" }]
export const nodes = [{ name: "East Legon Gateway", type: "CORE", status: "ONLINE", latency: "18 ms", clients: "428" }, { name: "Osu Community Node", type: "ACCESS", status: "ONLINE", latency: "24 ms", clients: "271" }, { name: "Airport Residential", type: "ACCESS", status: "DEGRADED", latency: "82 ms", clients: "119" }]

export interface NetworkController { authorizeDevice(deviceId: string): Promise<{ ok: boolean }>; revokeDevice(deviceId: string): Promise<{ ok: boolean }>; getDeviceStatus(deviceId: string): Promise<Status>; disconnectSession(sessionId: string): Promise<{ ok: boolean }>; getNetworkStatus(): Promise<Status> }
export const sandboxNetworkController: NetworkController = { async authorizeDevice() { return { ok: true } }, async revokeDevice() { return { ok: true } }, async getDeviceStatus() { return "AUTHORIZED" }, async disconnectSession() { return { ok: true } }, async getNetworkStatus() { return "ONLINE" } }

export function statusTone(status: string) { return ({ ACTIVE: "success", SUCCESS: "success", AUTHORIZED: "success", ONLINE: "success", PENDING: "warning", DEGRADED: "warning", EXPIRED: "muted", FAILED: "danger", BLOCKED: "danger", OFFLINE: "danger" } as Record<string, string>)[status] ?? "muted" }
export const navItems = [{ label: "Overview", href: "/dashboard" }, { label: "Subscription", href: "/dashboard/subscription" }, { label: "Payments", href: "/dashboard/payments" }, { label: "Devices", href: "/dashboard/devices" }, { label: "Settings", href: "/dashboard/settings" }]
export const adminNav = [{ label: "Overview", href: "/admin" }, { label: "Customers", href: "/admin/customers" }, { label: "Subscriptions", href: "/admin/subscriptions" }, { label: "Payments", href: "/admin/payments" }, { label: "Devices", href: "/admin/devices" }, { label: "Network", href: "/admin/network" }, { label: "Reports", href: "/admin/reports" }, { label: "Audit log", href: "/admin/audit" }]
