"use client"

import Link from "next/link"
import { FormEvent, useState } from "react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { authErrorMessage, authRedirectUrl, createClient } from "@/lib/supabase/client"

export default function Register() {
  const router = useRouter(); const [form, setForm] = useState({ name: "", phone: "", email: "", password: "" }); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); setMessage(""); const { data, error: signUpError } = await createClient().auth.signUp({ email: form.email, password: form.password, options: { emailRedirectTo: authRedirectUrl(), data: { full_name: form.name, phone: form.phone } } }); if (signUpError) { setError(authErrorMessage(signUpError.message)); setPending(false); return } if (data.session) { const provisionResponse = await fetch("/api/customers/provision", { method: "POST" }); if (!provisionResponse.ok) { setError("Account created, but we could not finish setting up your customer profile."); setPending(false); return } router.push("/dashboard") } else setMessage("Account created. Check your email to confirm access."); setPending(false) }
  return <main className="grid min-h-screen place-items-center px-5 py-8"><div className="glass w-full max-w-md rounded-2xl p-7"><Link href="/" className="text-xs font-bold tracking-[.2em] text-primary">STILLA CONNECT</Link><h1 className="mt-8 text-2xl font-semibold">Create your account.</h1><p className="mt-2 text-sm text-muted-foreground">Get started with managed community Internet.</p><form onSubmit={submit} className="mt-7 flex flex-col gap-4"><label className="flex flex-col gap-2 text-xs font-medium">Full name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className="h-10 rounded-lg border border-input bg-background/50 px-3 text-sm outline-none focus:border-primary" placeholder="Kwame Mensah" /></label><label className="flex flex-col gap-2 text-xs font-medium">Phone number<input required value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} className="h-10 rounded-lg border border-input bg-background/50 px-3 text-sm outline-none focus:border-primary" placeholder="+233 24 000 0000" /></label><label className="flex flex-col gap-2 text-xs font-medium">Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} className="h-10 rounded-lg border border-input bg-background/50 px-3 text-sm outline-none focus:border-primary" placeholder="you@example.com" /></label><label className="flex flex-col gap-2 text-xs font-medium">Password<input required minLength={8} type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} className="h-10 rounded-lg border border-input bg-background/50 px-3 text-sm outline-none focus:border-primary" placeholder="At least 8 characters" /></label>{error && <p role="alert" className="text-xs text-destructive">{error}</p>}{message && <p role="status" className="text-xs text-primary">{message}</p>}<Button disabled={pending} className="mt-2 w-full">{pending ? "Creating account…" : "Create account"}</Button></form><p className="mt-6 text-center text-xs text-muted-foreground">Already registered? <Link href="/login" className="text-primary">Sign in</Link></p></div></main>
}
